sudo: false

language: c

addons:
    apt:
        packages:
        - r-base
        - python3
        - ghc
        - git
        - libgsl0-dev

# adapted from Stack documentation at https://docs.haskellstack.org/en/v1.0.2/travis_ci/
before_install:
    - R -e 'install.packages("jsonlite", repos="https://cloud.r-project.org")'
    # Download and unpack the stack executable
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack --no-terminal build
  - stack --no-terminal install
  - morloc install rbase
  - morloc install math
  - morloc install cppbase
  - stack --no-terminal test

cache:
  directories:
    - $HOME/.stack
