# This travis file is adapted from fpco/wai-middleware-crowd

# Use c since it is light, then install everything needed for Haskell
language: c

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - sudo apt-get install r-base

# stack will handle the installation of GHC
script:
  - stack --no-terminal --install-ghc
  - morloc install rbase
  - morloc install math
  - morloc install cppbase

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack
