name:             morloc
version:          0.15.1
homepage:         https://github.com/arendsee/morloc
synopsis:         A multi-lingual, typed, workflow language
description:      See GitHub README <https://github.com/githubuser/morloc#readme>
category:         Compiler
license:          GPL-3
license-file:     LICENSE
author:           "Zebulun Arendsee" 
maintainer:       "zbwrbz@gmail.com"
github:           "arendsee/morloc"
bug-reports:      https://github.com/arendsee/morloc/issues
copyright:        "2018 Zebulun Arendsee"

extra-source-files:
  - README.md
  - ChangeLog.md
  - data/common/*.json

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - directory
  - docopt
  - extra
  - filepath
  - hashable
  - haskell-src-meta
  - megaparsec
  - mtl
  - network-uri
  - parsec
  - rdf4h
  - safe
  - scientific
  - template-haskell
  - text
  - unordered-containers
  - vector
  - wl-pprint-text
  - xml
  - HTTP

library:
  source-dirs: library

executables:
  morloc:
    main:          Main.hs
    source-dirs:   executable
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - morloc 
      - rdf4h
      - text

tests:
  morloc-test:
    main:          Main.hs
    source-dirs:   test-suite
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - directory
      - morloc
      - rdf4h
      - tasty
      - tasty-golden
      - tasty-hspec >= 0.1
      - temporary
      - text
