name:             morloc
version:          0.23.0-dev
homepage:         https://github.com/morloc-project/morloc
synopsis:         A multi-lingual, typed, workflow language
description:      See GitHub README <https://github.com/morloc-project/morloc#readme>
category:         Compiler
license:          GPL-3
license-file:     LICENSE
author:           "Zebulun Arendsee" 
maintainer:       "zbwrbz@gmail.com"
github:           "morloc-project/morloc"
bug-reports:      https://github.com/morloc-project/morloc/issues
copyright:        "2020 Zebulun Arendsee"

extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - directory
  - extra
  - filepath
  - haskell-src-meta
  - megaparsec
  - mtl
  - parsec
  - partial-order
  - pretty-simple
  - prettyprinter
  - prettyprinter-ansi-terminal
  - process
  - safe
  - scientific
  - template-haskell
  - text
  - unordered-containers
  - yaml

default-extensions:
  - FlexibleContexts
  - OverloadedStrings
  - BangPatterns
  - GeneralizedNewtypeDeriving
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-unused-binds
  - -fwarn-unused-imports 
  - -fwarn-tabs
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates
  - -fwarn-redundant-constraints
  - -fno-warn-missing-signatures
  - -fno-warn-unused-do-bind
  - -fno-warn-orphans

library:
  source-dirs: library

executables:
  morloc:
    main:          Main.hs
    source-dirs:   executable
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - morloc 
      - docopt
      - text

tests:
  morloc-test:
    main:          Main.hs
    source-dirs:   test-suite
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - morloc
      - QuickCheck
      - tasty
      - tasty-quickcheck
      - tasty-hunit
      - tasty-golden
