name:             morloc
version:          0.13.1
homepage:         https://github.com/arendsee/morloc
synopsis:         A multi-lingual, typed, workflow language
description:      See GitHub README <https://github.com/githubuser/morloc#readme>
category:         Compiler
license:          GPL-3
license-file:     LICENSE
author:           "Zebulun Arendsee" 
maintainer:       "zbwrbz@gmail.com"
github:           "arendsee/morloc"
bug-reports:      https://github.com/arendsee/morloc/issues
copyright:        "2018 Zebulun Arendsee"

extra-source-files:
  - README.md
  - data/common/*.json

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - extra
  - safe
  - megaparsec
  - parsec
  - network-uri
  - text
  - haskell-src-meta
  - rdf4h
  - hashable
  - HTTP
  - aeson
  - scientific
  - containers
  - unordered-containers
  - vector
  - template-haskell
  - mtl
  - wl-pprint-text
  - xml

library:
  source-dirs: library

executables:
  morloc:
    main:          Main.hs
    source-dirs:   executable
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >=4.7 && <5
      - rdf4h
      - text
      - morloc 

tests:
  morloc-test:
    main:          Main.hs
    source-dirs:   test-suite
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - tasty
      - tasty-hspec >= 0.1
      - morloc
      - rdf4h
      - text
