name:             morloc
version:          0.17.4-dev
homepage:         https://github.com/morloc-project/morloc
synopsis:         A multi-lingual, typed, workflow language
description:      See GitHub README <https://github.com/morloc-project/morloc#readme>
category:         Compiler
license:          GPL-3
license-file:     LICENSE
author:           "Zebulun Arendsee" 
maintainer:       "zbwrbz@gmail.com"
github:           "morloc-project/morloc"
bug-reports:      https://github.com/morloc-project/morloc/issues
copyright:        "2018 Zebulun Arendsee"

extra-source-files:
  - README.md
  - ChangeLog.md
  - data/common/*.json

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - directory
  - extra
  - filepath
  - haskell-src-meta
  - hsparql
  - megaparsec
  - mtl
  - parsec
  - pretty-simple
  - process
  - rdf4h
  - safe
  - scientific
  - template-haskell
  - text
  - unordered-containers
  - wl-pprint-text
  - yaml

extra-deps:
  - github: github/semantic
    commit: 38198bcf1ee25b09e2ce3fbcfc452f07892f6799

ghc-options:
  - -Wall
  - -XFlexibleContexts
  - -XOverloadedStrings
  - -Wcompat
  - -fwarn-unused-binds
  - -fwarn-unused-imports 
  - -fwarn-tabs
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates
  - -fwarn-redundant-constraints
  - -fno-warn-missing-signatures
  - -fno-warn-unused-do-bind

library:
  source-dirs: library

executables:
  morloc:
    main:          Main.hs
    source-dirs:   executable
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - morloc 
      - docopt
      - rdf4h
      - text

tests:
  morloc-test:
    main:          Main.hs
    source-dirs:   test-suite
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - directory
      - morloc
      - rdf4h
      - tasty
      - tasty-golden
      - text
